 Network jefersonbaixo_api_network  Creating
 Network jefersonbaixo_api_network  Created
 Container postgres  Creating
 Container postgres  Created
 Container api02-phoenix  Creating
 Container api01-phoenix  Creating
 Container api02-phoenix  Created
 Container api01-phoenix  Created
 Container nginx  Creating
 Container nginx  Created
Attaching to api01-phoenix, api02-phoenix, nginx, postgres
postgres       | 
postgres       | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres       | 
postgres       | 2024-03-08 16:12:24.315 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres       | 2024-03-08 16:12:24.315 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres       | 2024-03-08 16:12:24.315 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres       | 2024-03-08 16:12:24.321 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres       | 2024-03-08 16:12:24.330 UTC [30] LOG:  database system was shut down at 2024-03-06 22:06:45 UTC
postgres       | 2024-03-08 16:12:24.338 UTC [1] LOG:  database system is ready to accept connections
nginx          | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx          | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx          | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx          | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx          | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx          | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx          | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx          | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx          | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx          | 2024/03/08 16:12:30 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.28.0.3:4000/clientes/1/extrato", host: "localhost:9999"
nginx          | 2024/03/08 16:12:30 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.28.0.4:4001/clientes/1/extrato", host: "localhost:9999"
api01-phoenix  | 16:12:31.346 [info] Running RinhaDeBackend2024Q1Web.Endpoint with cowboy 2.10.0 at :::4000 (http)
api01-phoenix  | 16:12:31.347 [info] Access RinhaDeBackend2024Q1Web.Endpoint at https://api01
api02-phoenix  | 16:12:31.529 [info] Running RinhaDeBackend2024Q1Web.Endpoint with cowboy 2.10.0 at :::4001 (http)
api02-phoenix  | 16:12:31.530 [info] Access RinhaDeBackend2024Q1Web.Endpoint at https://api02
nginx          | 2024/03/08 16:12:32 [error] 30#30: *4 no live upstreams while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx          | 2024/03/08 16:12:34 [error] 30#30: *5 no live upstreams while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx          | 2024/03/08 16:12:36 [error] 30#30: *6 no live upstreams while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx          | 2024/03/08 16:12:38 [error] 30#30: *7 no live upstreams while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx          | 2024/03/08 16:12:40 [error] 30#30: *8 no live upstreams while connecting to upstream, client: 172.28.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api02-phoenix  | 16:12:42.219 request_id=F7rWDYxd9BWUQEUAAAPh [info] GET /clientes/1/extrato
postgres       | 2024-03-08 16:12:42.247 UTC [53] ERROR:  relation "customers" does not exist at character 51
postgres       | 2024-03-08 16:12:42.247 UTC [53] STATEMENT:  SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api02-phoenix  | 16:12:42.322 request_id=F7rWDYxd9BWUQEUAAAPh [info] Sent 500 in 103ms
api02-phoenix  | 16:12:42.325 [error] #PID<0.424.0> running RinhaDeBackend2024Q1Web.Endpoint (connection #PID<0.423.0>, stream id 1) terminated
api02-phoenix  | Server: api:80 (http)
api02-phoenix  | Request: GET /clientes/1/extrato
api02-phoenix  | ** (exit) an exception was raised:
api02-phoenix  |     ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "customers" does not exist
api02-phoenix  | 
api02-phoenix  |     query: SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api02-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
api02-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1/customers/get.ex:16: RinhaDeBackend2024Q1.Customers.Get.call/1
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:10: RinhaDeBackend2024Q1Web.CustomersController.show/2
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:1: RinhaDeBackend2024Q1Web.CustomersController.action/2
api02-phoenix  | 16:12:44.331 request_id=F7rWDgpOgsdnFw0AAAQh [info] GET /clientes/1/extrato
postgres       | 2024-03-08 16:12:44.331 UTC [52] ERROR:  relation "customers" does not exist at character 51
postgres       | 2024-03-08 16:12:44.331 UTC [52] STATEMENT:  SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api02-phoenix  | 16:12:44.332 request_id=F7rWDgpOgsdnFw0AAAQh [info] Sent 500 in 859Âµs
api02-phoenix  | 16:12:44.332 [error] #PID<0.426.0> running RinhaDeBackend2024Q1Web.Endpoint (connection #PID<0.425.0>, stream id 1) terminated
api02-phoenix  | Server: api:80 (http)
api02-phoenix  | Request: GET /clientes/1/extrato
api02-phoenix  | ** (exit) an exception was raised:
api02-phoenix  |     ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "customers" does not exist
api02-phoenix  | 
api02-phoenix  |     query: SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api02-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
api02-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1/customers/get.ex:16: RinhaDeBackend2024Q1.Customers.Get.call/1
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:10: RinhaDeBackend2024Q1Web.CustomersController.show/2
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:1: RinhaDeBackend2024Q1Web.CustomersController.action/2
api01-phoenix  | 16:12:46.371 request_id=F7rWDoPdxy2UQEUAAAPh [info] GET /clientes/1/extrato
postgres       | 2024-03-08 16:12:46.433 UTC [42] ERROR:  relation "customers" does not exist at character 51
postgres       | 2024-03-08 16:12:46.433 UTC [42] STATEMENT:  SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api01-phoenix  | 16:12:46.449 request_id=F7rWDoPdxy2UQEUAAAPh [info] Sent 500 in 77ms
api01-phoenix  | 16:12:46.451 [error] #PID<0.424.0> running RinhaDeBackend2024Q1Web.Endpoint (connection #PID<0.423.0>, stream id 1) terminated
api01-phoenix  | Server: api:80 (http)
api01-phoenix  | Request: GET /clientes/1/extrato
api01-phoenix  | ** (exit) an exception was raised:
api01-phoenix  |     ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "customers" does not exist
api01-phoenix  | 
api01-phoenix  |     query: SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api01-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
api01-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1/customers/get.ex:16: RinhaDeBackend2024Q1.Customers.Get.call/1
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:10: RinhaDeBackend2024Q1Web.CustomersController.show/2
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:1: RinhaDeBackend2024Q1Web.CustomersController.action/2
api02-phoenix  | 16:12:48.458 request_id=F7rWDwBLKMfUgs0AAARB [info] GET /clientes/1/extrato
postgres       | 2024-03-08 16:12:48.458 UTC [57] ERROR:  relation "customers" does not exist at character 51
postgres       | 2024-03-08 16:12:48.458 UTC [57] STATEMENT:  SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api02-phoenix  | 16:12:48.459 request_id=F7rWDwBLKMfUgs0AAARB [info] Sent 500 in 958Âµs
api02-phoenix  | 16:12:48.459 [error] #PID<0.428.0> running RinhaDeBackend2024Q1Web.Endpoint (connection #PID<0.427.0>, stream id 1) terminated
api02-phoenix  | Server: api:80 (http)
api02-phoenix  | Request: GET /clientes/1/extrato
api02-phoenix  | ** (exit) an exception was raised:
api02-phoenix  |     ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "customers" does not exist
api02-phoenix  | 
api02-phoenix  |     query: SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api02-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
api02-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1/customers/get.ex:16: RinhaDeBackend2024Q1.Customers.Get.call/1
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:10: RinhaDeBackend2024Q1Web.CustomersController.show/2
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:1: RinhaDeBackend2024Q1Web.CustomersController.action/2
api01-phoenix  | 16:12:50.466 request_id=F7rWD3gAUohnFw0AAAQh [info] GET /clientes/1/extrato
postgres       | 2024-03-08 16:12:50.467 UTC [50] ERROR:  relation "customers" does not exist at character 51
postgres       | 2024-03-08 16:12:50.467 UTC [50] STATEMENT:  SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api01-phoenix  | 16:12:50.467 request_id=F7rWD3gAUohnFw0AAAQh [info] Sent 500 in 900Âµs
api01-phoenix  | 16:12:50.467 [error] #PID<0.426.0> running RinhaDeBackend2024Q1Web.Endpoint (connection #PID<0.425.0>, stream id 1) terminated
api01-phoenix  | Server: api:80 (http)
api01-phoenix  | Request: GET /clientes/1/extrato
api01-phoenix  | ** (exit) an exception was raised:
api01-phoenix  |     ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "customers" does not exist
api01-phoenix  | 
api01-phoenix  |     query: SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api01-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
api01-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1/customers/get.ex:16: RinhaDeBackend2024Q1.Customers.Get.call/1
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:10: RinhaDeBackend2024Q1Web.CustomersController.show/2
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:1: RinhaDeBackend2024Q1Web.CustomersController.action/2
api02-phoenix  | 16:12:52.474 request_id=F7rWD--zjX8VLTsAAARh [info] GET /clientes/1/extrato
postgres       | 2024-03-08 16:12:52.475 UTC [61] ERROR:  relation "customers" does not exist at character 51
postgres       | 2024-03-08 16:12:52.475 UTC [61] STATEMENT:  SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api02-phoenix  | 16:12:52.475 request_id=F7rWD--zjX8VLTsAAARh [info] Sent 500 in 919Âµs
api02-phoenix  | 16:12:52.476 [error] #PID<0.430.0> running RinhaDeBackend2024Q1Web.Endpoint (connection #PID<0.429.0>, stream id 1) terminated
api02-phoenix  | Server: api:80 (http)
api02-phoenix  | Request: GET /clientes/1/extrato
api02-phoenix  | ** (exit) an exception was raised:
api02-phoenix  |     ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "customers" does not exist
api02-phoenix  | 
api02-phoenix  |     query: SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api02-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
api02-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1/customers/get.ex:16: RinhaDeBackend2024Q1.Customers.Get.call/1
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:10: RinhaDeBackend2024Q1Web.CustomersController.show/2
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:1: RinhaDeBackend2024Q1Web.CustomersController.action/2
api01-phoenix  | 16:12:54.483 request_id=F7rWEGdnZ5zUgs0AAARB [info] GET /clientes/1/extrato
postgres       | 2024-03-08 16:12:54.483 UTC [44] ERROR:  relation "customers" does not exist at character 51
postgres       | 2024-03-08 16:12:54.483 UTC [44] STATEMENT:  SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api01-phoenix  | 16:12:54.484 request_id=F7rWEGdnZ5zUgs0AAARB [info] Sent 500 in 852Âµs
api01-phoenix  | 16:12:54.484 [error] #PID<0.428.0> running RinhaDeBackend2024Q1Web.Endpoint (connection #PID<0.427.0>, stream id 1) terminated
api01-phoenix  | Server: api:80 (http)
api01-phoenix  | Request: GET /clientes/1/extrato
api01-phoenix  | ** (exit) an exception was raised:
api01-phoenix  |     ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "customers" does not exist
api01-phoenix  | 
api01-phoenix  |     query: SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api01-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
api01-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1/customers/get.ex:16: RinhaDeBackend2024Q1.Customers.Get.call/1
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:10: RinhaDeBackend2024Q1Web.CustomersController.show/2
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:1: RinhaDeBackend2024Q1Web.CustomersController.action/2
api02-phoenix  | 16:12:56.492 request_id=F7rWEN8jLti0O7wAAASB [info] GET /clientes/1/extrato
postgres       | 2024-03-08 16:12:56.492 UTC [58] ERROR:  relation "customers" does not exist at character 51
postgres       | 2024-03-08 16:12:56.492 UTC [58] STATEMENT:  SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api02-phoenix  | 16:12:56.492 request_id=F7rWEN8jLti0O7wAAASB [info] Sent 500 in 851Âµs
api02-phoenix  | 16:12:56.493 [error] #PID<0.432.0> running RinhaDeBackend2024Q1Web.Endpoint (connection #PID<0.431.0>, stream id 1) terminated
api02-phoenix  | Server: api:80 (http)
api02-phoenix  | Request: GET /clientes/1/extrato
api02-phoenix  | ** (exit) an exception was raised:
api02-phoenix  |     ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "customers" does not exist
api02-phoenix  | 
api02-phoenix  |     query: SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api02-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
api02-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1/customers/get.ex:16: RinhaDeBackend2024Q1.Customers.Get.call/1
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:10: RinhaDeBackend2024Q1Web.CustomersController.show/2
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:1: RinhaDeBackend2024Q1Web.CustomersController.action/2
api01-phoenix  | 16:12:58.500 request_id=F7rWEVbUT9gVLTsAAARh [info] GET /clientes/1/extrato
postgres       | 2024-03-08 16:12:58.500 UTC [46] ERROR:  relation "customers" does not exist at character 51
postgres       | 2024-03-08 16:12:58.500 UTC [46] STATEMENT:  SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api01-phoenix  | 16:12:58.500 request_id=F7rWEVbUT9gVLTsAAARh [info] Sent 500 in 847Âµs
api01-phoenix  | 16:12:58.501 [error] #PID<0.430.0> running RinhaDeBackend2024Q1Web.Endpoint (connection #PID<0.429.0>, stream id 1) terminated
api01-phoenix  | Server: api:80 (http)
api01-phoenix  | Request: GET /clientes/1/extrato
api01-phoenix  | ** (exit) an exception was raised:
api01-phoenix  |     ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "customers" does not exist
api01-phoenix  | 
api01-phoenix  |     query: SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api01-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
api01-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1/customers/get.ex:16: RinhaDeBackend2024Q1.Customers.Get.call/1
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:10: RinhaDeBackend2024Q1Web.CustomersController.show/2
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:1: RinhaDeBackend2024Q1Web.CustomersController.action/2
api02-phoenix  | 16:13:00.508 request_id=F7rWEc6F24zZbfkAAASh [info] GET /clientes/1/extrato
postgres       | 2024-03-08 16:13:00.508 UTC [55] ERROR:  relation "customers" does not exist at character 51
postgres       | 2024-03-08 16:13:00.508 UTC [55] STATEMENT:  SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api02-phoenix  | 16:13:00.509 request_id=F7rWEc6F24zZbfkAAASh [info] Sent 500 in 907Âµs
api02-phoenix  | 16:13:00.509 [error] #PID<0.434.0> running RinhaDeBackend2024Q1Web.Endpoint (connection #PID<0.433.0>, stream id 1) terminated
api02-phoenix  | Server: api:80 (http)
api02-phoenix  | Request: GET /clientes/1/extrato
api02-phoenix  | ** (exit) an exception was raised:
api02-phoenix  |     ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "customers" does not exist
api02-phoenix  | 
api02-phoenix  |     query: SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api02-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
api02-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1/customers/get.ex:16: RinhaDeBackend2024Q1.Customers.Get.call/1
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:10: RinhaDeBackend2024Q1Web.CustomersController.show/2
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:1: RinhaDeBackend2024Q1Web.CustomersController.action/2
api01-phoenix  | 16:13:02.516 request_id=F7rWEkY2sNu0O7wAAASB [info] GET /clientes/1/extrato
postgres       | 2024-03-08 16:13:02.516 UTC [47] ERROR:  relation "customers" does not exist at character 51
postgres       | 2024-03-08 16:13:02.516 UTC [47] STATEMENT:  SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api01-phoenix  | 16:13:02.517 request_id=F7rWEkY2sNu0O7wAAASB [info] Sent 500 in 810Âµs
api01-phoenix  | 16:13:02.517 [error] #PID<0.432.0> running RinhaDeBackend2024Q1Web.Endpoint (connection #PID<0.431.0>, stream id 1) terminated
api01-phoenix  | Server: api:80 (http)
api01-phoenix  | Request: GET /clientes/1/extrato
api01-phoenix  | ** (exit) an exception was raised:
api01-phoenix  |     ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "customers" does not exist
api01-phoenix  | 
api01-phoenix  |     query: SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api01-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
api01-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1/customers/get.ex:16: RinhaDeBackend2024Q1.Customers.Get.call/1
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:10: RinhaDeBackend2024Q1Web.CustomersController.show/2
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:1: RinhaDeBackend2024Q1Web.CustomersController.action/2
api02-phoenix  | 16:13:04.524 request_id=F7rWEr3mTMpMvh0AAATB [info] GET /clientes/1/extrato
postgres       | 2024-03-08 16:13:04.524 UTC [59] ERROR:  relation "customers" does not exist at character 51
postgres       | 2024-03-08 16:13:04.524 UTC [59] STATEMENT:  SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api02-phoenix  | 16:13:04.525 request_id=F7rWEr3mTMpMvh0AAATB [info] Sent 500 in 877Âµs
api02-phoenix  | 16:13:04.525 [error] #PID<0.436.0> running RinhaDeBackend2024Q1Web.Endpoint (connection #PID<0.435.0>, stream id 1) terminated
api02-phoenix  | Server: api:80 (http)
api02-phoenix  | Request: GET /clientes/1/extrato
api02-phoenix  | ** (exit) an exception was raised:
api02-phoenix  |     ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "customers" does not exist
api02-phoenix  | 
api02-phoenix  |     query: SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api02-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
api02-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
api02-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1/customers/get.ex:16: RinhaDeBackend2024Q1.Customers.Get.call/1
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:10: RinhaDeBackend2024Q1Web.CustomersController.show/2
api02-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:1: RinhaDeBackend2024Q1Web.CustomersController.action/2
api01-phoenix  | 16:13:06.532 request_id=F7rWEzWZ3i_ZbfkAAASh [info] GET /clientes/1/extrato
postgres       | 2024-03-08 16:13:06.533 UTC [48] ERROR:  relation "customers" does not exist at character 51
postgres       | 2024-03-08 16:13:06.533 UTC [48] STATEMENT:  SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api01-phoenix  | 16:13:06.533 request_id=F7rWEzWZ3i_ZbfkAAASh [info] Sent 500 in 902Âµs
api01-phoenix  | 16:13:06.533 [error] #PID<0.434.0> running RinhaDeBackend2024Q1Web.Endpoint (connection #PID<0.433.0>, stream id 1) terminated
api01-phoenix  | Server: api:80 (http)
api01-phoenix  | Request: GET /clientes/1/extrato
api01-phoenix  | ** (exit) an exception was raised:
api01-phoenix  |     ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "customers" does not exist
api01-phoenix  | 
api01-phoenix  |     query: SELECT c0."id", c0."balance", c0."max_limit" FROM "customers" AS c0 WHERE (c0."id" = $1)
api01-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
api01-phoenix  |         (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
api01-phoenix  |         (ecto 3.11.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1/customers/get.ex:16: RinhaDeBackend2024Q1.Customers.Get.call/1
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:10: RinhaDeBackend2024Q1Web.CustomersController.show/2
api01-phoenix  |         (rinha_de_backend_2024_q1 0.1.0) lib/rinha_de_backend_2024_q1_web/controllers/customers_controller.ex:1: RinhaDeBackend2024Q1Web.CustomersController.action/2
nginx exited with code 0
nginx exited with code 0
api02-phoenix  | 16:13:09.391 [notice] SIGTERM received - shutting down
api02-phoenix  | 
api01-phoenix  | 16:13:09.392 [notice] SIGTERM received - shutting down
api01-phoenix  | 
api02-phoenix  | 16:13:09.402 [info] Postgrex.Protocol (#PID<0.296.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api02-phoenix  | 16:13:09.403 [info] Postgrex.Protocol (#PID<0.297.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api02-phoenix  | 16:13:09.403 [info] Postgrex.Protocol (#PID<0.294.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api02-phoenix  | 16:13:09.403 [info] Postgrex.Protocol (#PID<0.298.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api02-phoenix  | 16:13:09.403 [info] Postgrex.Protocol (#PID<0.301.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api02-phoenix  | 16:13:09.403 [info] Postgrex.Protocol (#PID<0.302.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api02-phoenix  | 16:13:09.403 [info] Postgrex.Protocol (#PID<0.300.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api02-phoenix  | 16:13:09.403 [info] Postgrex.Protocol (#PID<0.299.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api02-phoenix  | 16:13:09.403 [info] Postgrex.Protocol (#PID<0.295.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api01-phoenix  | 16:13:09.404 [info] Postgrex.Protocol (#PID<0.297.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api01-phoenix  | 16:13:09.404 [info] Postgrex.Protocol (#PID<0.296.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api01-phoenix  | 16:13:09.404 [info] Postgrex.Protocol (#PID<0.295.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api01-phoenix  | 16:13:09.404 [info] Postgrex.Protocol (#PID<0.298.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api01-phoenix  | 16:13:09.404 [info] Postgrex.Protocol (#PID<0.301.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api01-phoenix  | 16:13:09.404 [info] Postgrex.Protocol (#PID<0.302.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api01-phoenix  | 16:13:09.404 [info] Postgrex.Protocol (#PID<0.299.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api01-phoenix  | 16:13:09.404 [info] Postgrex.Protocol (#PID<0.300.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api01-phoenix  | 16:13:09.404 [info] Postgrex.Protocol (#PID<0.294.0>) missed message: {:EXIT, #PID<0.314.0>, :shutdown}
api01-phoenix exited with code 0
api01-phoenix exited with code 0
api02-phoenix exited with code 0
api02-phoenix exited with code 0
postgres       | 2024-03-08 16:13:11.406 UTC [1] LOG:  received fast shutdown request
postgres       | 2024-03-08 16:13:11.411 UTC [1] LOG:  aborting any active transactions
postgres       | 2024-03-08 16:13:11.413 UTC [1] LOG:  background worker "logical replication launcher" (PID 33) exited with exit code 1
postgres       | 2024-03-08 16:13:11.413 UTC [28] LOG:  shutting down
postgres       | 2024-03-08 16:13:11.418 UTC [28] LOG:  checkpoint starting: shutdown immediate
postgres       | 2024-03-08 16:13:11.470 UTC [28] LOG:  checkpoint complete: wrote 40 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.008 s, sync=0.025 s, total=0.057 s; sync files=10, longest=0.007 s, average=0.003 s; distance=228 kB, estimate=228 kB; lsn=0/1954C00, redo lsn=0/1954C00
postgres       | 2024-03-08 16:13:11.473 UTC [1] LOG:  database system is shut down
postgres exited with code 0
